# Minecraft version
minecraft_version=1.20.1
# Fabric Loader version
loader_version=0.14.22
# Fabric API version
fabric_version=0.83.0+1.20.1

# Mod Information
mod_version=1.0.0
maven_group=com.example
archives_base_name=golxden-client

# Java Version Settings
# This tells the computer to use Java 21 for everything
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64